import React, { useState, createContext } from "react";

export const StoreContext = createContext({});

export const StoreContextProvider = ({ user, children }) => {
  const [personal, setPersonal] = useState({
    idCard: "1234567890123",
    govCard: "1234567890",
    cardExpire: user && user.cardExpire ? user.cardExpire : "2024-12-31",
    prefixName: "นาย",
    firstName: user ? user.firstName : undefined,
    lastName: user ? user.lastName : undefined,
    birthDate: user && user.birthDate ? user.birthDate : "1990-04-01",
    race: "ไทย",
    nation: "ไทย",
  });
  // const [personal, setPersonal] = useState({
  //   idCard: undefined,
  //   govCard: undefined,
  //   cardExpire: user && user.cardExpire ? user.cardExpire : undefined,
  //   prefixName: undefined,
  //   firstName: user ? user.firstName : undefined,
  //   lastName: user ? user.lastName : undefined,
  //   birthDate: user && user.birthDate ? user.birthDate : null,
  //   race: undefined,
  //   nation: undefined,
  // });
  const [address, setAddress] = useState({
    domicileNo: "21/3",
    domicileMoo: "4",
    domicileSoi: undefined,
    domicileRoad: undefined,
    domicileProvince: 57,
    domicileDistrict: 801,
    domicileSubDistrict: 7114,
    domicileZipcode: 72140,
    domicileTel: "0822543216",
    domicileFax: undefined,
    domicileEmail: "thongchai@email.com",
    addressNo: "1470/106",
    addressMoo: undefined,
    addressSoi: "14",
    addressRoad: "เสนานิคม 1",
    addressProvince: 1,
    addressDistrict: 30,
    addressSubDistrict: 179,
    addressZipcode: 10900,
    addressTel: "0822543216",
    addressFax: undefined,
    addressEmail: "thongchai@email.com",
    contactNo: undefined,
    contactMoo: undefined,
    contactSoi: undefined,
    contactRoad: undefined,
    contactProvince: undefined,
    contactDistrict: undefined,
    contactSubDistrict: undefined,
    contactZipcode: undefined,
    contactTel: undefined,
    contactFax: undefined,
    contactEmail: undefined,
  });
  // const [address, setAddress] = useState({
  //   domicileNo: undefined,
  //   domicileMoo: undefined,
  //   domicileSoi: undefined,
  //   domicileRoad: undefined,
  //   domicileProvince: undefined,
  //   domicileDistrict: undefined,
  //   domicileSubDistrict: undefined,
  //   domicileZipcode: undefined,
  //   domicileTel: undefined,
  //   domicileFax: undefined,
  //   domicileEmail: undefined,
  //   addressNo: undefined,
  //   addressMoo: undefined,
  //   addressSoi: undefined,
  //   addressRoad: undefined,
  //   addressProvince: undefined,
  //   addressDistrict: undefined,
  //   addressSubDistrict: undefined,
  //   addressZipcode: undefined,
  //   addressTel: undefined,
  //   addressFax: undefined,
  //   addressEmail: undefined,
  //   contactNo: undefined,
  //   contactMoo: undefined,
  //   contactSoi: undefined,
  //   contactRoad: undefined,
  //   contactProvince: undefined,
  //   contactDistrict: undefined,
  //   contactSubDistrict: undefined,
  //   contactZipcode: undefined,
  //   contactTel: undefined,
  //   contactFax: undefined,
  //   contactEmail: undefined,
  // });
  const [work, setWork] = useState({
    workOccupation: "รับราชการ",
    workPosition: "นักวิชาการคอมพิวเตอร์ปฏิบัติการ",
    workPlaces: "ศาลยุติธรรม",
    workRoad: "รัชดาภิเษก",
    workSubDistrict: 182,
    workDistrict: 30,
    workProvince: 1,
    workZipcode: 10900,
    workTel: "0822543216",
    workFax: undefined,
    workEmail: "thongchai@email.com",
    bossFirstName: "เจอร์เกน",
    bossLastName: "คล็อปป์",
    bossNo: "111",
    bossMoo: undefined,
    bossSoi: undefined,
    bossRoad: "รัชดาภิเษก",
    bossSubDistrict: 182,
    bossDistrict: 30,
    bossProvince: 1,
    bossZipcode: 10900,
    bossTel: "0822543210",
    bossFax: undefined,
    bossEmail: "Klopp@email.com",
    workExperience: "1. บ.กิฟฟารีน สกายไลน์ ยูนิตี้ จำกัด\n2. กรมบัญชีกลาง",
  });
  // const [work, setWork] = useState({
  //   workOccupation: undefined,
  //   workPosition: undefined,
  //   workPlaces: undefined,
  //   workRoad: undefined,
  //   workSubDistrict: undefined,
  //   workDistrict: undefined,
  //   workProvince: undefined,
  //   workZipcode: undefined,
  //   workTel: undefined,
  //   workFax: undefined,
  //   workEmail: undefined,
  //   bossFirstName: undefined,
  //   bossLastName: undefined,
  //   bossNo: undefined,
  //   bossMoo: undefined,
  //   bossSoi: undefined,
  //   bossRoad: undefined,
  //   bossSubDistrict: undefined,
  //   bossDistrict: undefined,
  //   bossProvince: undefined,
  //   bossZipcode: undefined,
  //   bossTel: undefined,
  //   bossFax: undefined,
  //   bossEmail: undefined,
  //   workExperience: undefined,
  // });

  const [regis, setRegis] = useState({
    splTypeID: 1,
    splSubTypeID: 4,
    regisQualification: "ปริญญาตรี",
    regisDocument: "1. สำเนาบัตรประชาชน\n2. สำเนาทะเบียนบ้าน",
    regisEver: "การแพทย์",
    regisEverYear: 2560,
    regisEverPass: undefined,
    regisEverPassNo: 123456,
    regisEverNopass: undefined,
    regisEverNopassDesc: undefined,
  });

  // const [regis, setRegis] = useState({
  //   splTypeID: undefined,
  //   splSubTypeID: undefined,
  //   regisQualification: undefined,
  //   regisDocument: undefined,
  //   regisEver: undefined,
  //   regisEverYear: undefined,
  //   regisEverPass: undefined,
  //   regisEverPassNo: undefined,
  //   regisEverNopass: undefined,
  //   regisEverNopassDesc: undefined,
  // });

  const store = {
    personal: [personal, setPersonal],
    address: [address, setAddress],
    work: [work, setWork],
    regis: [regis, setRegis],
  };
  return (
    <StoreContext.Provider value={store}>{children}</StoreContext.Provider>
  );
};
